### ISSUE TITLE
EXCEPTION_DURING_VALUE_LOOKUP InvalidCastException while viewing MSNT_SystemTrace/SystemConfig/ProcessorGroup event

### ISSUE THREAD

**Issue by MagicAndre1981** [microsoft/perfview#707]
When I view the MSNT_SystemTrace/SystemConfig/ProcessorGroup event, I see an InvalidCastException:

```
<Event MSec= "20559,6537" PID=  "-1" PName=        "" TID=  "-1" EventName="SystemConfig/ProcessorGroup"
  TimeStamp="06.29.18 17:23:22.272978" ID="Illegal" Version="2" Keywords="0x00000000" TimeStampQPC="71.241.516.466" QPCTime="0,100us"
  Level="Always" ProviderName="MSNT_SystemTrace" ProviderGuid="9e814aad-3204-11d2-9a82-006008a86939" ClassicProvider="True" ProcessorNumber="5"
  Opcode="26" TaskGuid="01853a65-418f-4f36-aefc-dc0f1d2fd235" Channel="0" PointerSize="8"
  CPU="5" EventIndex="1329036" TemplateType="DynamicTraceEventData">
  <PrettyPrint>
    <Event MSec= "20559,6537" PID=  "-1" PName=        "" TID=  "-1" EventName="SystemConfig/ProcessorGroup" ProviderName="MSNT_SystemTrace" Affinity="&lt;&lt;&lt;EXCEPTION_DURING_VALUE_LOOKUP InvalidCastException&gt;&gt;&gt;"/>
  </PrettyPrint>
  <Payload Length="12">
       0:   1  0  0  0 ff  0  0  0 |  0  0  0  0               ........ ....
  </Payload>
</Event>
```

The trace is from an Insider Build:

`BuildLab="17692.1000.amd64fre.rs_prerelease.180609-1317" ProductName="Windows 10 Pro" `

**Comment by brianrob** [comment]
@MagicAndre1981 it is possible that this has been resolved in the OS.  Does this repro on a shipped build of Windows?

**Comment by MagicAndre1981** [comment]
@brianrob still happens in 18362.449 (this is most current stable).

Run `WPR -start CPU -start Power ` and `WPR -stop C:\cpu_power.etl`. Now open the ETL in perfview and here I get the issue while trying to decode the event.

I use Perfview 2.0.46 to load the ETL.

**Comment by brianrob** [comment]
Thanks for confirming @MagicAndre1981.

**Comment by MagicAndre1981** [comment]
I still see this casting error in the most recent PerfView version on Windows 11 23H2.

**Comment by brianrob** [comment]
> I still see this casting error in the most recent PerfView version on Windows 11 23H2.

Thanks @MagicAndre1981.  I have a fix out for this.

**Comment by MagicAndre1981** [comment]
> Thanks [@MagicAndre1981](https://github.com/MagicAndre1981). I have a fix out for this.

the Fix works for me.

`<Event MSec= "42988.4096" PID=  "-1" PName=        "" TID=  "-1" EventName="SystemConfig/ProcessorGroup" ProviderName="MSNT_SystemTrace" Affinity="[255]"/>`

**Comment by brianrob** [comment]
> > Thanks [@MagicAndre1981](https://github.com/MagicAndre1981). I have a fix out for this.
> 
> the Fix works for me.
> 
> `<Event MSec= "42988.4096" PID= "-1" PName= "" TID= "-1" EventName="SystemConfig/ProcessorGroup" ProviderName="MSNT_SystemTrace" Affinity="[255]"/>`

Awesome!  Thanks for testing this!
