### ISSUE TITLE
Don't refresh if combo boxes unchanged

### ISSUE THREAD

**Issue by drewnoakes** [microsoft/perfview#783]
1. Open the GroupPats combo box
2. Close it without changing anything
3. UI is blocked while the tree refreshes, which I believe is unnecessary

This is true of other combo boxes as well.

PerfView v2.0.26

**Comment by drewnoakes** [comment]
Looks like this was addressed in #1851 and this issue not closed.

**Comment by brianrob** [comment]
Thanks @drewnoakes!  I wonder how many bugs we have out there that are actually fixed but not resolved...
