### ISSUE TITLE
TraceParserGen error on Microsoft-Windows-NDIS-PacketCapture

### ISSUE THREAD

**Issue by vancem** [Microsoft/perfview#808]
Repo steps.   
```
K:\source\perfview\src\PerfView\bin\Release\net45>PerfView.exe /nogui userCommand DumpRegisteredManifest Microsoft-Windows-NDIS-PacketCapture

K:\source\perfview\src\PerfView\bin\Release\net45>k:\source\perfview\src\TraceParserGen\bin\Release\net40\TraceParserGen.exe Microsoft-Windows-NDIS-PacketCapture.manifest.xml
Reading manifest file Microsoft-Windows-NDIS-PacketCapture.manifest.xml
Error: Error on line Microsoft-Windows-NDIS-PacketCapture.manifest.xml(37,9): An item with the same key has already been added.
```

From the look of the XML file (what is on line 37) the issue is that two tasks have the same opcode.  This should be supported, but evidently it has broken.     Should be easy to fix.

**Comment by vancem** [comment]
This is fixed by #808

**Comment by OfekShilon** [comment]
I'm afraid I'm running the updated code, and still unable to generate C#
code for Kernel-Network
